
server:
  port: 20237
  servlet:
    context-path: /api

spring:
  application-name: "Gestion Conges Server"
  datasource:
    url: jdbc:mysql://udfkuwapm4tehtbp:kofbP5QErRBh6Ne79a7@bdr8adqa2yb0x7txmwiz-mysql.services.clever-cloud.com:20237/bdr8adqa2yb0x7txmwiz
    username: udfkuwapm4tehtbp
    password: kofbP5QErRBh6Ne79a7
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      ddl-auto: "update"
